dist: trusty
sudo: false

language: bash

env:
  - PASS_VERSION=1.7.3
  - PASS_VERSION=master

addons:
  apt:
    packages:
      - cabal-install
      - expect
      - ghc
      - oathtool

before_script:
  - hot/password-store-$PASS_VERSION.tar.xz
  - tar -xvf password-store-$PASS_VERSION.tar.xz
  - ln -s password-store.sh pass
  - if llcheck" ]; then cabal update; cabal install ShellCheck; fi
  lcheck" 
  - export PATH=$PATH:.
  - export TEST_OPT

install: true



cache:
  directories:
    

script:
  - 
  - cd ake all

notifications:
  email:
    recipients:
      - tadfis@gm
    on_success: never
    on_failure: always
